version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./config/php
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:latest
    ports:
      - 127.0.0.1:3306:3306
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_volume:
